const configuredSiteUrl = import.meta.env.PUBLIC_SITE_URL;

export const site = {
  name: "Klein Grant Portfolio",
  title: "Klein Grant | Senior Programmer & Technical Artist",
  description:
    "10+ years of experience as a senior programmer and technical artist across game development, VR/AR, tooling, shaders, and web platforms.",
  url: configuredSiteUrl || "https://kakem.github.io/portfolio-kei",
  author: "Klein Grant",
  locale: "en_US",
  ogImage: "/og-image.jpg",
  favicon: "/favicon.svg",
  navBrand: {
    image: "/logo.png",
    imageAlt: "Klein Grant logo",
  },
  heroVisual: {
    enabled: true,
    mode: "three-ascii-split",
    renderMode: "pixelSample",
    debugGui: {
      enabled: false,
      showInProduction: false,
      startOpen: true,
      width: 360,
      enableWithQueryParam: true,
    },
    modelSource: "url",
    asciiSide: "right",
    splitPosition: 0.5,
    splitAngle: 0,
    splitSoftness: 0.00,
    showSplitLine: false,
    modelUrl: "/media/hero/StylizedPC.glb",
    modelMaterialMode: "force-unlit",
    modelTextureSource: "embedded",
    modelTextureUrl: "/media/hero/combinedBake.webp",
    modelAnimation: {
      enabled: false,
      clip: "first",
      loop: true,
      clampWhenFinished: true,
      timeScale: 1,
    },
    modelView: {
      cameraDistance: 7.2,
      cameraY: 0.55,
      cameraFov: 38,
      modelFitSize: 5,
      position: {
        x: 1.35,
        y: 0.05,
        z: 0,
      },
    },
    fallbackImage: "/media/hero/hero-fallback.png",
    fallbackTint: {
      color: "rgba(87, 213, 255, 0.22)",
      blendMode: "multiply",
    },
    mediaOverlay: {
      visible: true,
      opacity: 0,
    },
    backgroundTitle: {
      enabled: true,
      text: "ART & CODE;",
      normalColor: "rgba(244, 247, 251, 1)",
      asciiColor: "rgba(87, 213, 255, 1)",
      opacity: 1,
      fontSize: "clamp(5rem, 16vw, 13rem)",
      mobileFontSize: "clamp(2.8rem, 17vw, 5.5rem)",
      x: "0%",
      y: "-30%",
    },
    ascii: {
    enabled: true,
    densityMode: "fixed-cell",
    resolution: 180,
    cellWidth: 8,
    updateFPS: 15,
    charset: "  .-01/10",
    invert: false,
    sampleCount: 4,
    samplePattern: "grid",
    contrast: 1.1,
    brightness: 4,
    gamma: 1.83,
    edgeBoost: 0.91,
    edgeThreshold: 1,
    surfaceFill: true,
    surfaceFillStrength: 0.35,
    surfacePointDensity: 0.25,
    useDepthForBrightness: true,
    depthBrightnessStrength: 0.45,
    useNormalLighting: true,
    normalLightingStrength: 0.5,
    edgeDominance: 0.8,
    pixelSampleDisableOnMobile: false,
    colorSampling: {
      enabled: true,
      mode: "average",
      blendMode: "lighten",
      strength: 1,
      saturation: 3,
      brightness: 3,
      contrast: 1,
      alpha: 1,
      grayscaleFallback: false,
      sampleBackground: false,
      minAlpha: 0.07,
      forceVisibleColorCells: false,
      minimumCharacter: ".",
      minimumColorLuminance: 0.05,
      visibilityBoost: 0.35,
      disableOnMobile: false,
    },
    cellAspect: 1.8,
    fontSize: 10,
    lineHeight: 10,
    useShapeAwareLookup: false,
    shapeVectorMode: "6d",
    useCachedLookup: true,
    lookupQuantization: 8,
    maxCacheEntries: 10000,
    disableOnMobile: false,
  },
    maxPixelRatio: 1.5,
    enableOrbitControls: true,
    orbit: {
      enableDamping: true,
      dampingFactor: 0.06,
      enableZoom: false,
      enablePan: false,
      autoRotate: true,
      autoRotateSpeed: 0.35,
      minPolarAngle: 1.1,
      maxPolarAngle: 2.05,
      minAzimuthAngle: -Infinity,
      maxAzimuthAngle: Infinity,
      rotateSpeed: 0.45,
      touchRotateSpeed: 0.35,
      disableOnMobile: false,
    },
    disableOnMobile: false,
  },
  pages: {
    home: {
      path: "/",
      title: "Klein Grant | Senior Programmer & Technical Artist",
      description:
        "A visual portfolio for Unity, Unreal Engine, VR/AR, technical art, tooling, and full-stack web development work.",
    },
    projects: {
      path: "/projects",
      title: "Featured Projects",
      description:
        "Selected projects highlighting game development, technical art, tools, shaders, optimization, and interactive media.",
    },
    gallery: {
      path: "/gallery",
      title: "Gallery",
      description:
        "A visual collection of environments, characters, animation tests, editor tools, 3D assets, pixel art, GIFs, and video work.",
    },
    about: {
      path: "/about",
      title: "About",
      description: "Background, interests, and creative direction as a game developer and technical artist.",
    },
    experience: {
      path: "/experience",
      title: "Experience / Skills",
      description: "Professional experience, technical skills, soft skills, tools, languages, and production background.",
    },
    contact: {
      path: "/contact",
      title: "Contact",
      description: "Download my CV, view professional profiles, or contact me directly.",
    },
  },
  galleryMasonry: {
    mobile: 2,
    tablet: 2,
    desktop: 4,
    wide: 4,
  },
  galleryThumbnail: {
    showMediaType: false,
    showTags: false,
    showTitle: false,
    showDescription: false,
    generatedWidth: 640,
    generatedFormat: "webp",
    generatedQuality: 78,
    fullImageMaxWidth: 1800,
    fullImageQuality: 86,
  },
  projectThumbnail: {
    showDescription: false,
  },
  experienceTimeline: {
    homeLimit: 2,
    pageLimit: null,
  },
  pageHeaders: {
    projects: {
      eyebrow: "Selected Work",
      title: "Featured Projects",
      intro:
        "Selected projects highlighting my work in game development, technical art, tools, shaders, optimization, and interactive media.",
      backgroundImage: "/src/featuredHeader.png",
      backgroundAlt: "Abstract project showcase background",
      visualAccent: "#57d5ff",
    },
    gallery: {
      eyebrow: "Visual Archive",
      title: "Gallery",
      intro:
        "A visual collection of environments, characters, animation tests, editor tools, 3D assets, pixel art, GIFs, and video work.",
      backgroundImage: "/src/visualHeader.png",
      backgroundAlt: "Abstract gallery contact sheet background",
      visualAccent: "#ffcf5a",
    },
    about: {
      eyebrow: "Profile",
      title: "About",
      intro: "Background, interests, and creative direction as a game developer and technical artist.",
      backgroundImage: "/src/aboutHeader.png",
      backgroundAlt: "Abstract portrait and workspace background",
      visualAccent: "#ff6f91",
    },
    experience: {
      eyebrow: "Resume",
      title: "Experience / Skills",
      intro: "Professional experience, technical skills, soft skills, tools, languages, and production background.",
      backgroundImage: "/src/experenceHeader.png",
      backgroundAlt: "Abstract production timeline background",
      visualAccent: "#8effd2",
    },
    contact: {
      eyebrow: "Contact",
      title: "Contact",
      intro: "Download my CV, view professional profiles, or contact me directly.",
      backgroundImage: "/media/page-bg/contact-bg.svg",
      backgroundAlt: "Abstract communication links background",
      visualAccent: "#ffcf5a",
    },
  },
};

export type SiteConfig = typeof site;
