const configuredSiteUrl = import.meta.env.PUBLIC_SITE_URL;

export const site = {
  name: "Kei Portfolio",
  title: "Kei | Game Developer & Technical Artist",
  description:
    "A visual portfolio for a game developer and technical artist focused on realtime tools, shaders, gameplay prototypes, and interactive media.",
  url: configuredSiteUrl || "https://kakem.github.io/portfolio-kei",
  author: "Kei",
  locale: "en_US",
  ogImage: "/og-image.jpg",
  favicon: "/favicon.svg",
  heroVisual: {
    enabled: true,
    mode: "three-ascii-split",
    renderMode: "edgeProjection",
    debugGui: {
      enabled: true,
      showInProduction: false,
      startOpen: true,
      width: 360,
      enableWithQueryParam: true,
    },
    modelSource: "url",
    asciiSide: "right",
    splitPosition: 0.5,
    splitAngle: 0,
    splitSoftness: 0.00,
    showSplitLine: false,
    modelUrl: "/media/hero/StylizedPC.glb",
    modelMaterialMode: "force-unlit",
    modelTextureSource: "embedded",
    modelTextureUrl: "/media/hero/combinedBake.webp",
    modelAnimation: {
      enabled: false,
      clip: "first",
      loop: true,
      clampWhenFinished: true,
      timeScale: 1,
    },
    modelView: {
      cameraDistance: 7.2,
      cameraY: 0.55,
      cameraFov: 38,
      modelFitSize: 6,
      position: {
        x: 1.35,
        y: 0.05,
        z: 0,
      },
    },
    fallbackImage: "/media/hero/hero-fallback.webp",
    fallbackTint: {
      color: "rgba(87, 213, 255, 0.22)",
      blendMode: "multiply",
    },
    mediaOverlay: {
      visible: true,
      opacity: 0,
    },
    backgroundTitle: {
      enabled: true,
      text: "ART // CODE",
      normalColor: "rgba(244, 247, 251, 1)",
      asciiColor: "rgba(87, 213, 255, 1)",
      opacity: 1,
      fontSize: "clamp(5rem, 16vw, 13rem)",
      x: "0%",
      y: "-30%",
    },
    ascii: {
      enabled: true,
      densityMode: "fixed-cell",
      resolution: 180,
      cellWidth: 8,
      updateFPS: 30,
      charset: " .:-=+*#%@",
      invert: false,
      sampleCount: 4,
      samplePattern: "grid",
      contrast: 1.4,
      brightness: 1,
      gamma: 1,
      edgeBoost: 0.35,
      edgeThreshold: 0.2,
      surfaceFill: true,
      surfaceFillStrength: 0.35,
      surfacePointDensity: 0.25,
      useDepthForBrightness: true,
      depthBrightnessStrength: 0.45,
      useNormalLighting: true,
      normalLightingStrength: 0.5,
      edgeDominance: 0.8,
      pixelSampleDisableOnMobile: false,
      colorSampling: {
        enabled: false,
        mode: "average",
        strength: 1,
        saturation: 1,
        brightness: 1,
        contrast: 1,
        alpha: 1,
        grayscaleFallback: false,
        sampleBackground: false,
        minAlpha: 0.05,
        disableOnMobile: false,
      },
      cellAspect: 1.8,
      fontSize: 10,
      lineHeight: 10,
      useShapeAwareLookup: false,
      shapeVectorMode: "6d",
      useCachedLookup: true,
      lookupQuantization: 8,
      maxCacheEntries: 10000,
      disableOnMobile: false,
    },
    maxPixelRatio: 1.5,
    enableOrbitControls: true,
    orbit: {
      enableDamping: true,
      dampingFactor: 0.06,
      enableZoom: false,
      enablePan: false,
      autoRotate: true,
      autoRotateSpeed: 0.35,
      minPolarAngle: 1.1,
      maxPolarAngle: 2.05,
      minAzimuthAngle: -Infinity,
      maxAzimuthAngle: Infinity,
      rotateSpeed: 0.45,
      touchRotateSpeed: 0.35,
      disableOnMobile: false,
    },
    disableOnMobile: false,
  },
  pages: {
    home: {
      path: "/",
      title: "Kei | Game Developer & Technical Artist",
      description:
        "A visual portfolio for realtime prototypes, technical art, shaders, tools, and game development work.",
    },
    projects: {
      path: "/projects",
      title: "Featured Projects",
      description:
        "Selected projects highlighting game development, technical art, tools, shaders, optimization, and interactive media.",
    },
    gallery: {
      path: "/gallery",
      title: "Gallery",
      description:
        "A visual collection of environments, characters, animation tests, editor tools, 3D assets, pixel art, GIFs, and video work.",
    },
    about: {
      path: "/about",
      title: "About",
      description: "Background, interests, and creative direction as a game developer and technical artist.",
    },
    experience: {
      path: "/experience",
      title: "Experience / Skills",
      description: "Professional experience, technical skills, soft skills, tools, languages, and production background.",
    },
    contact: {
      path: "/contact",
      title: "Contact",
      description: "Download my CV, view professional profiles, or contact me directly.",
    },
  },
  galleryMasonry: {
    mobile: 1,
    tablet: 2,
    desktop: 3,
    wide: 4,
  },
  pageHeaders: {
    projects: {
      eyebrow: "Selected Work",
      title: "Featured Projects",
      intro:
        "Selected projects highlighting my work in game development, technical art, tools, shaders, optimization, and interactive media.",
      backgroundImage: "/media/page-bg/projects-bg.svg",
      backgroundAlt: "Abstract project showcase background",
      visualAccent: "#57d5ff",
    },
    gallery: {
      eyebrow: "Visual Archive",
      title: "Gallery",
      intro:
        "A visual collection of environments, characters, animation tests, editor tools, 3D assets, pixel art, GIFs, and video work.",
      backgroundImage: "/media/page-bg/gallery-bg.svg",
      backgroundAlt: "Abstract gallery contact sheet background",
      visualAccent: "#ffcf5a",
    },
    about: {
      eyebrow: "Profile",
      title: "About",
      intro: "Background, interests, and creative direction as a game developer and technical artist.",
      backgroundImage: "/media/page-bg/about-bg.svg",
      backgroundAlt: "Abstract portrait and workspace background",
      visualAccent: "#ff6f91",
    },
    experience: {
      eyebrow: "Resume",
      title: "Experience / Skills",
      intro: "Professional experience, technical skills, soft skills, tools, languages, and production background.",
      backgroundImage: "/media/page-bg/experience-bg.svg",
      backgroundAlt: "Abstract production timeline background",
      visualAccent: "#8effd2",
    },
    contact: {
      eyebrow: "Contact",
      title: "Contact",
      intro: "Download my CV, view professional profiles, or contact me directly.",
      backgroundImage: "/media/page-bg/contact-bg.svg",
      backgroundAlt: "Abstract communication links background",
      visualAccent: "#ffcf5a",
    },
  },
};

export type SiteConfig = typeof site;
